apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: daeseopjeongpipelinesjavascriptdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: daeseopjeongpipelinesjavascriptdocker 
    spec:
      containers:
        - name: daeseopjeongpipelinesjavascriptdocker 
          image: user19containerregistry.azurecr.io/daeseopjeongpipelinesjavascriptdocker
          ports:
          - containerPort: 8080